api-version: '${api_version}'
authors: ['TetraTheta']
dependencies:
  server:
    WorldEdit:
      join-classpath: true
      load: BEFORE
      required: true
    WorldGuard:
      join-classpath: true
      load: BEFORE
      required: true
load: POSTWORLD
main: io.github.tetratheta.farmmanager.FarmManager
name: FarmManager
version: '${version}'
permissions:
  farmmanager.admin:
    default: op
    description: Manage FarmManager settings and watched WorldGuard regions
